FROM node:20-alpine
WORKDIR /app
EXPOSE 3000
CMD ["node", "-e", "require('http').createServer((req,res)=>res.end('backend placeholder')).listen(3000)"]

npm install node
npm install express
npm install  nodemon
npm install sequelize
npm install pg pg-hstore

